services:
  dagster-webserver:
    ports:
      - "12000:12000"
    depends_on:
      dagster-postgres:
        condition: service_healthy
    environment:
      - POSTGRES_PASSWORD=dagster_postgres_pwd
      - DEFINITIONS=prod
    volumes:
      - ./data:/opt/app/data

  dagster-postgres:
    image: "postgres:latest"
    user: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: dagster_postgres_pwd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-p", "5432" ]
      interval: 3s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config/prod/dagster_storage
