telemetry:
  enabled: false
sensors:
  use_threads: true
  num_workers: 8
schedules:
  use_threads: true
  num_workers: 8
storage:
  sqlite:
    base_dir: config/dev/dagster_storage
compute_logs:
  module: dagster.core.storage.local_compute_log_manager
  class: LocalComputeLogManager
  config:
    base_dir: config/dev/dagster_storage
local_artifact_storage:
  module: dagster.core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir: config/dev/dagster_storage
code_servers:
  local_startup_timeout: 300
run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    max_concurrent_runs: 32
    dequeue_interval_seconds: 1
    dequeue_use_threads: true
    dequeue_num_workers: 32
    user_code_failure_retry_delay: 5
run_monitoring:
  enabled: true
  free_slots_after_run_end_seconds: 15 # free any hanging concurrency slots after 15 seconds from the end of a run
